# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 09:57
from __future__ import unicode_literals

import django.contrib.gis.db.models.fields
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ARObject',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('timeCreated', models.DateTimeField(auto_now_add=True)),
                ('owner', models.TextField()),
                ('description', models.TextField()),
                ('location', django.contrib.gis.db.models.fields.PointField(srid=4326)),
                ('asset', models.FileField(upload_to='media')),
            ],
            options={
                'ordering': ('timeCreated',),
            },
        ),
    ]
