# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2017-10-07 13:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('radDB', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='arobject',
            name='asset',
            field=models.FileField(null=True, upload_to=''),
        ),
    ]
